[Eth]
NetworkId = 15279
SyncMode = "full"

[Node]
HTTPHost = "localhost"
HTTPPort = 3545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["personal", "eth", "net", "web3", "admin", "miner", "txpool", "debug"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = "localhost"
WSPort = 3546
WSModules = ["personal", "eth", "net", "web3", "admin", "miner", "txpool", "debug"]
GraphQLVirtualHosts = ["localhost"]


[Node.P2P]
MaxPeers = 200
NoDiscovery = false
BootstrapNodes = ["enode://9e108ef566eda51dc6e912da3a2fe716c674f74c88b5d53a9b9a478ea918310f1aeb755153417ecf379e7bb4ba2c8ccb25cda3dcc7ace60704a6f0a3210e2bac@202.143.109.174:40606"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":40605"
